AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - spec/integration/*
    - rung.gemspec

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Metrics/LineLength:
  IgnoredPatterns:
    - ^\s*it \'
