:toc: right
:backend: html5
:doctitle: Living Documentation
:doctype: book
:icons: font
:!numbered:
:!linkcss:
:sectanchors:
:sectlink:
:docinfo:
:source-highlighter: highlightjs
:toclevels: 3
:hardbreaks:
:chapter-label: Chapter
:version-label: Version

= *Living Documentation*


== *Features*

[[failure, failure]]
=== *failure*

ifndef::backend-pdf[]
minmax::failure[]
endif::[]
****
Operation call returns `Rung::Runner::Result` object that can be either a success or a failure.
  Result has `success?` and `failure?` methods.
****

==== Scenario: When all steps return truthy value the result is a success

==========
Given ::
definition icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
----

class Operation < Rung::Base
  step do
    # do something...
    true
  end

  step :second_step

  def second_step
    2 + 2
  end
end

----
When ::
I run icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
----

@result = Operation.new.call

----
Then ::
I can assure that icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
----

@result.success? == true

----
And ::
I can assure that icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
----

@result.failure? == false

----
==========

==== Scenario: When at least one step returns a falsy value then the result is a failure

==========
Given ::
definition icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
----

class Operation < Rung::Base
  step do
    # do something...
    true
  end

  step :second_step

  def second_step
    nil
  end
end

----
When ::
I run icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
----

@result = Operation.new.call

----
Then ::
I can assure that icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
----

@result.success? == false

----
And ::
I can assure that icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
----

@result.failure? == true

----
==========

==== Scenario: When a step fails then the next steps are not executed

==========
Given ::
definition icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
----

class Operation < Rung::Base
  step do
    print_to_output "Hello"
    true
  end

  step do
    # something went wrong, retuning false
    false
  end

  step do
    print_to_output "World"
  end
end

----
When ::
I run icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
----

Operation.new.call

----
Then ::
I see output icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
----

Hello

----
==========

[[state, state]]
=== *state*

ifndef::backend-pdf[]
minmax::state[]
endif::[]
==== Scenario: State is shared across step executions

==========
Given ::
definition icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
----

class Operation < Rung::Base
  step do |state|
    state[:what] = "World!"
  end

  step do
    print_to_output "Hello "
  end

  step do |state|
    print_to_output state[:what]
  end
end

----
When ::
I run icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
----

Operation.new.call

----
Then ::
I see output icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
----

Hello World!

----
==========

==== Scenario: State is available in the result object

==========
Given ::
definition icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
----

class Operation < Rung::Base
  step do |state|
    state[:output_text] = "Hello "
  end

  step do |state|
    state[:output_text] << "World!"
  end
end

----
When ::
I run icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
----

@result = Operation.new.call

----
Then ::
I can assure that icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
----

@result[:output_text] == "Hello World!"

----
==========

==== Scenario: Initial state can be passed to call method

==========
Given ::
definition icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
----

class Operation < Rung::Base
  step do |state|
    state[:output_text] << "World!"
  end
end

----
When ::
I run icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
----

@result = Operation.new.call(output_text: "Hello ")

----
Then ::
I can assure that icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
----

@result[:output_text] == "Hello World!"

----
==========

[[steps_definition, steps_definition]]
=== *steps_definition*

ifndef::backend-pdf[]
minmax::steps_definition[]
endif::[]
****
There are multiple ways of defining steps.
  Steps definition order is important as they are always executed in order.
****

==== Scenario: Steps can be defined as a Ruby block

==========
Given ::
definition icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
----

class Operation < Rung::Base
  step do |state|
    state[:what] = "World"
  end

  step do
    print_to_output "Hello "
  end

  step do |state|
    print_to_output state[:what]
  end

  step do
    print_to_output "!"
  end
end

----
When ::
I run icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
----

Operation.new.call

----
Then ::
I see output icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
----

Hello World!

----
==========

==== Scenario: Steps can be defined as methods

==========
Given ::
definition icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
----

class Operation < Rung::Base
  step :set_what_state
  step :print_hello
  step "print_what"
  step :print_bang

  def set_what_state(state)
    state[:what] = "World"
  end

  def print_hello
    print_to_output "Hello "
  end

  def print_what(state)
    print_to_output state[:what]
  end

  def print_bang
    print_to_output "!"
  end
end

----
When ::
I run icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
----

Operation.new.call

----
Then ::
I see output icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
----

Hello World!

----
==========

==== Scenario: Steps can be defined as any objects with call method

==========
Given ::
definition icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
----

class SetWhatState
  def initialize(what)
    @what = what
  end

  def call(state)
    state[:what] = @what
  end
end

class PrintHello
  def self.call
    print_to_output "Hello "
  end
end

class PrintWhat
  def self.call(state)
    print_to_output state[:what]
  end
end

PrintBang = -> { print_to_output "!" }

class Operation < Rung::Base
  step SetWhatState.new("World")
  step PrintHello
  step PrintWhat
  step PrintBang
end

----
When ::
I run icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
----

Operation.new.call

----
Then ::
I see output icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
----

Hello World!

----
==========

